before_script:
    - export PARROT_RELEASE=5_3_0
    - wget https://github.com/parrot/parrot/archive/$PARROT_RELEASE.zip
    - unzip $PARROT_RELEASE
    - cd parrot-parrot*
    - pwd
    - perl Configure.pl --prefix="/tmp/installed_parrot" && make install
    - export PATH=/tmp/installed_parrot/bin/:$PATH
    - cd ..

# This sets up the Rosella submodule
before_install:
    - git submodule update --init --recursive

script: "winxed setup.winxed build && winxed setup.winxed test"

# branches:
#   only:
#     - master
notifications:
  recipients:
    - duke@leto.net
  email:
    on_success: change
    on_failure: always
#env:
