before_script:
    - wget https://nodeload.github.com/parrot/parrot/zipball/RELEASE_4_0_0
    - unzip RELEASE_4_0_0
    - cd parrot-parrot*
    - pwd
    - perl Configure.pl --prefix="/tmp/installed_parrot" && make install
    - export PATH=/tmp/installed_parrot/bin/:$PATH
    - cd ..
script: "winxed setup.winxed build && winxed setup.winxed test"
# branches:
#   only:
#     - master
notifications:
  recipients:
    - duke@leto.net
  email:
    on_success: change
    on_failure: always
#env:
